/**
 * Workflow instructions written into file-based recipe targets (cursor, aider,
 * factory, opencode, junie, windsurf, cody, kilocode) and used as the default
 * body of every `kind: "section"` managed block (codex, mux, agents).
 *
 * Two variants matching the `--agents-profile <minimal|full>` choice:
 *
 *   - **`WORKFLOW_BODY` (full)** — a self-contained command reference plus
 *     a pointer at `linear prime` for full context. Used by tools without
 *     Claude Code plugin support that need the cheat-sheet inline: cursor,
 *     aider, factory, opencode, junie, windsurf, cody, kilocode. Also the
 *     default body of managed-section recipes (codex, mux, agents) where
 *     the user file may be consumed by any agent. Also what
 *     `linear setup --print` / `linear setup -o <path>` emit, so
 *     copy-paste users get the canonical reference.
 *
 *   - **`WORKFLOW_BODY_MINIMAL` (minimal)** — a short pointer at
 *     `linear prime` plus a hint about `/plugin install linear` for
 *     Claude Code hosts that bundle the dedicated skill. Used by the
 *     agent-skill snapshot (`plugins/linear/...` host already discovers the
 *     full skill on its own) and the `agents` section recipe (which is
 *     intentionally short — the onboard equivalent).
 *
 * Recipes embed their own per-editor markdown framing (`---\nalwaysApply:
 * true\n---\n` for cursor, plain markdown elsewhere). The content body is
 * identical across recipes that share a variant — only the file extension and
 * path differ. Each recipe entry wraps the chosen variant if needed (cursor
 * prepends front-matter via `CURSOR_TEMPLATE`).
 *
 * Surrounding BEGIN/END markers let users manually edit around the block
 * without losing it on reinstall.
 */
export const WORKFLOW_BODY = `# Linear Issue Tracking
# Auto-generated by 'linear setup' - do not remove these markers
# BEGIN LINEAR INTEGRATION

This project uses [linear](https://github.com/HumanInTheLoopReal/linear) — a CLI for Linear.app (human-readable text by default, \`--json\` for agents and scripts) — for issue tracking.

## Core Rules
- Track durable outcomes, decisions, independently resumable work, human gates,
  and next actions in Linear; use the host agent's task system for temporary steps
- Treat issue creation as backlog commitment: execution workers create only
  necessary children under assigned work; unrelated discoveries wait for triage
- Use \`linear next\` (or \`linear ready\`) to find available work
- Search before creation and preserve the approved project/parent hierarchy
- Use \`linear preflight\` before sending a PR

## Quick Reference
\`\`\`bash
linear prime                              # Load complete workflow context
linear next                               # Show next issue to work on
linear issues list --status open,in_progress # List all non-terminal issues
linear issues create "..." --parent-ticket <parent> --dry-run # Preview approved child
linear start <id>                          # Claim + In Progress; one selector owns selection
linear issues close <id> --reason "..."   # Only after the real terminal gate
linear depends add <issue> <depends-on>   # Add dependency
\`\`\`

## Workflow
1. Verify repository policy and scope with \`linear where\`
2. Select approved ready work with \`linear next\`
3. Claim through one selector with \`linear start <id>\`, then confirm state
4. Use agent tasks for temporary execution; use Linear children only for
   independently resumable required work
5. Capture unrelated discoveries as findings for triage
6. Tend review/CI/merge, post one receipt, and close only after the real gate

## Context Loading
Run \`linear prime\` to get complete workflow documentation in agent-optimized format.

For Claude Code users: \`/plugin install linear\` bundles the dedicated skill, slash commands (\`/linear:list\`, \`/linear:ready\`, \`/linear:show\`, \`/linear:prime\`, ...), and resource docs alongside this file.

For detailed docs: see USAGE.md or run \`linear --help\`.

# END LINEAR INTEGRATION
`;

/**
 * Minimal pointer variant. Used where the host already has its own
 * discovery surface for the linear workflow (the agent-skill snapshot at
 * `.agents/skills/linear/SKILL.md`, which is a copy of the canonical
 * `.claude/skills/linear/SKILL.md`; the generic `agents` managed-block
 * section, intentionally short).
 *
 * For Claude Code hosts that support plugins, the snippet steers the user
 * at `/plugin install linear` — that pulls down the full skill, slash
 * commands, and resource docs from `plugins/linear/` so the agent learns
 * the workflow without inlining the command reference here.
 */
export const WORKFLOW_BODY_MINIMAL = `# Linear Issue Tracking
# Auto-generated by 'linear setup' - do not remove these markers
# BEGIN LINEAR INTEGRATION

This project uses **linear** (Linear.app CLI). Run \`linear prime\` for full workflow context, or for Claude Code users, run \`/plugin install linear\` to install the dedicated skill plus \`/linear:*\` slash commands.

**Quick reference:**
- \`linear next\` — find unblocked work
- \`linear start <id>\` — claim approved work through the owning selector
- \`linear issues create "Title" --parent-ticket <parent> --dry-run\` — preview an approved child
- \`linear issues close <id> --reason "..."\` — complete work after the real gate

Linear holds durable product truth; the agent task system holds temporary execution
steps. Unrelated discoveries wait for triage rather than becoming automatic backlog.

For everything else: \`linear prime\`.

# END LINEAR INTEGRATION
`;

/** Cursor expects a YAML front-matter `alwaysApply: true` before the rule body. */
export const CURSOR_TEMPLATE = `---
alwaysApply: true
---

${WORKFLOW_BODY}`;
