/**
 * `.aider.conf.yml` body for the aider multifile recipe.
 *
 * Aider reads this file (if present) on every invocation and treats
 * the entries under the `read:` key as auto-attached source files —
 * the project's coding agent sees them in its context window without
 * the user having to remember to `/add` them.
 *
 * We point aider at `.aider/LINEAR.md` so the linear workflow brief
 * is auto-loaded. Without this conf file, aider would have to be
 * told manually each session — defeating the install's purpose.
 */
export const AIDER_CONF_YML = `# Auto-generated by 'linear setup aider' — do not remove this block.
# Aider reads .aider.conf.yml on startup; entries under the "read" key
# are attached to the model's context on every invocation.
read:
  - .aider/LINEAR.md
`;
